[build]
  base = "."
  command = """
    python -m pip install --upgrade pip &&
    pip install -r requirements.txt &&
    python manage.py collectstatic --noinput
  """
  publish = "staticfiles"

[build.environment]
  PYTHON_VERSION = "3.8.12"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
